### ISSUE TITLE
Requirements.txt won't install

### ISSUE THREAD

**Issue by roman-larin** [Noob-Development/Sandbox-Mod-Installer#5]
`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: altgraph==0.17 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.17)
Requirement already satisfied: certifi==2020.12.5 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2020.12.5)
Requirement already satisfied: chardet==4.0.0 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: future==0.18.2 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.18.2)
Requirement already satisfied: idna==2.10 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.10)
Collecting numpy==1.20.1
  Using cached numpy-1.20.1.zip (7.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pefile==2019.4.18 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (2019.4.18)
Requirement already satisfied: Pillow==8.1.2 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (8.1.2)
Requirement already satisfied: pyinstaller==4.2 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (4.2)
Requirement already satisfied: pyinstaller-hooks-contrib==2021.1 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2021.1)
Requirement already satisfied: pywin32-ctypes==0.2.0 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.2.0)
Requirement already satisfied: requests==2.25.1 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2.25.1)
Requirement already satisfied: six==1.15.0 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.15.0)
Requirement already satisfied: urllib3==1.26.4 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (1.26.4)
Requirement already satisfied: wxPython==4.1.1 in /home/larin/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (4.1.1)
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from pyinstaller==4.2->-r requirements.txt (line 9)) (59.1.1)
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): finished with status 'error'
Failed to build numpy`

**Comment by Griffeng** [comment]
This project uses Python 3.8 make sure to have it installed and not a newer version as some packages haven't been updated.
